### Get departments
GET http://localhost:3000/departments

### Get department Query By Id
GET http://localhost:3000/departments/query/30


### Get department By Id
GET http://localhost:3000/departments/30

### Get department By Id
GET http://localhost:3000/departments/query/30

### Add department
POST http://localhost:3000/departments
Content-Type: application/json

{
    "department_id" : 280,
    "department_name" : "Operational",
    "manager_id" : null,
    "location_id" : 1700
}

### Update department
PUT http://localhost:3000/departments/280
Content-Type: application/json

{
    "department_id" : 280,
    "department_name" : "IT Operational",
    "manager_id" : null,
    "location_id" : 1700
}

### Delete department
DELETE http://localhost:3000/departments/280